name: "Setup"
description: "Setup Node.js"

runs:
  using: "composite"
  steps:
    - name: "Setup Node"
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version-file: 'package.json'
        cache: 'yarn'
    - name: "Install NPM Packages"
      run: yarn install --check-files --frozen-lockfile --non-interactive
      shell: bash
